### ISSUE TITLE
Question about evalution with torch

### ISSUE THREAD

**Issue by LiuYixian** [harvardnlp/data2text#17]
Hi,

When I run the evalution with
CUDA_VISIBLE_DEVICES=6 ~/torch/install/bin/th extractor.lua -gpuid 1 -datafile roto-ie.h5 -preddata drive_data/transform_gen/roto_cc-beam5_gens.h5 -dict_pfx "roto-ie" -just_eval, I'm faced with the following error.
/root/torch/install/bin/luajit: extractor.lua:574: bad argument #1 to 'copy' (sizes do not match at /root/torch/extra/cutorch/lib/THC/THCTensorCopy.cu:31)
I print the size and find that the size of p (parameters of generated model) is 2234733, and the size of saved_p (parameters from conv1ie-ep6-94-74.t7) is 2141733. How can I solve the problem?

My torch is installed with LuaJIT. The hdf5 is installed with 'luarocks install hdf5'.

Thank you

Yixian

**Comment by swiseman** [comment]
Unfortunately, it's become difficult to continue to support lua torch, because it doesn't really have formal versions. I would recommend using the information extractor from Ratish Puduppully's [repo](https://github.com/ratishsp/data2text-plan-py), which is much improved in any case, and is what nearly all subsequent work on this dataset has used.

**Comment by LiuYixian** [comment]
Oh, I run that repo but faced with the same problem.
