### ISSUE TITLE
"list index out of range" error when generating pointer file

### ISSUE THREAD

**Issue by Harold-Lee-PKU** [harvardnlp/data2text#4]
Hi, Sam, sorry to bother you again. When I tried to generate the pointer file, I encountered a "list index out of range" error at line 644 in "data_utils.py". Maybe there exists a minor mixup or something? It seems easy to fix.

**Comment by swiseman** [comment]
I was able to run without any problems on one computer, but I could reproduce your error on another; I believe the issue is related to the version of nltk. On nltk 3.2.1 (and probably earlier) this seems to be fine, but breaks on 3.2.4. Is there a reason you need to regnerate the train pointer file?

**Comment by Harold-Lee-PKU** [comment]
I am sorry I didn’t notice that the ptr file has been attached. Closing the issue...
